# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  MySQL-SetUp:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute SQL Queries full
        run: |
          
          SQL_SCRIPT_FILES=("sql_script1.sql")

          # Loop through the array and execute each SQL script
          for SQL_SCRIPT_FILE in "${SQL_SCRIPT_FILES[@]}"; do
            echo "Executing SQL script: $SQL_SCRIPT_FILE"
            
            
            SQL_SCRIPT_CONTENT=$(cat "$SQL_SCRIPT_FILE")

            # Execute the SQL script using the MySQL client 
            mysql -h localhost -u amal -p'${{ secrets.PASSWORD }}' -e "$SQL_SCRIPT_CONTENT"
          done
     
