# This is a basic workflow to help you get started with Actions

name: Shell script

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  shell-SetUp:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute script1 
        run: |
          chmod +x script1.sh
          ./script1.sh
          
      - name: Execute Script 2
        run: |
          chmod +x script2.sh
          ./script2.sh
          
      - name: Upload Outputs
        uses: actions/upload-artifact@v2
        with:
          name: script-outputs
          path: |
            output_script1.txt
            output_script2.txt
      
          
     
