# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  MySQL-SetUp:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute SQL Queries full
        run: |
          
          
     
